### PR TITLE
Port to more mature game engine

### PR DESCRIPTION
**Pull request by PJB3005**
Advantages:
* built-in account system
* better networking stack
* 5000 compiler warnings to lag your Rider
* half the install fee of Godot.

### CODE REVIEW

**Review by Visne — APPROVED** [review]

**Comment by Emisse** [comment]
the code is perfect

**Review by Emisse — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
no unit tests written for this PR, denied.

**Comment by Visne** [comment]
1984

**Comment by Jezithyr** [comment]
We have quite a *robust* unit testing framework 😏

**Pull request closed without merging**
